# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c5307ce65411a9642c5acfc2ecb0bf7f277edf62eb901089554aa1cf3da767f3761373479f188a9c0878c0ac0d86eb26645ee93c42fbc2df5e7af2f0abf4c7f

test:
  secret_key_base: 82c6b90a3cf4a6c3d3896afc1fa8c2580de66a5e39e7c86fa5fba5caa11b970aab63832bdf5fc3cace03145560b67b5a11277858859b286b250ee2b0898cfb26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
